# Generated by Django 4.2.3 on 2023-07-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0003_applicationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='Application',
        ),
    ]
