# Generated by Django 4.2.3 on 2023-07-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0004_rename_applicationform_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aboriginal',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='aboriginalChoices',
            field=models.CharField(choices=[('First Nations', 'First Nations'), ('Métis', 'Métis'), ('Inuit', 'Inuit')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='appTimesDropdown',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cei',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='firstApp',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='firstName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phoneNumber',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='preferredEmail',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='studentEmail',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='studentNumber',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='vertifyPreferredEmail',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='vertifyStudentEmail',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
