# Generated by Django 4.2.3 on 2023-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0005_application_aboriginal_application_aboriginalchoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
