# Generated by Django 4.2.3 on 2023-07-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0006_alter_application_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='aboriginal',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='firstApp',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10),
        ),
    ]
