# Generated by Django 4.2.3 on 2023-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0009_alter_application_aboriginal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicationNumber',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cwl',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='dateApplied',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
