# Generated by Django 4.2.3 on 2023-07-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0010_application_applicationnumber_application_cwl_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constants',
            new_name='Constant',
        ),
    ]
