# Generated by Django 4.2.3 on 2023-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0011_rename_constants_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
