# Generated by Django 4.2.3 on 2023-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0013_alter_constant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constant',
            name='date',
        ),
        migrations.AddField(
            model_name='constant',
            name='helpText',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
