# Generated by Django 4.2.3 on 2023-08-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieteticsApp', '0014_remove_constant_date_constant_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Applicant'},
        ),
        migrations.AlterModelOptions(
            name='constant',
            options={'ordering': ['name', 'value'], 'verbose_name': 'Constant'},
        ),
    ]
